# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet-SIDD-width128-remove-1.2-256-fix
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    multi:
    -   
      type: PairedImageDataset
      dataroot_gt: ./train_remove_dataset_768/gt.lmdb
      dataroot_lq: ./train_remove_dataset_768/lq.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: ./val_remove_dataset_768/gt.lmdb
    dataroot_lq: ./val_remove_dataset_768/lq.lmdb
    io_backend:
      type: lmdb


network_g:
  type: NAFNet
  width: 128
  enc_blk_nums: [2, 2, 4, 28]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]
  train_size: [1, 3, 256, 256]

# path
path:
  # pretrain_network_g: experiments/NAFNet-SIDD-width64-remove-fix/models/net_g_200000.pth
  pretrain_network_g: experiments/NAFNet-SIDD-width64-remove-1.0-fix/models/net_g_50000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 80000
    eta_min: !!float 1e-8

  total_iter: 80000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: ConcatLoss
    name:
    -
      type: MS_SSIMLoss
      loss_weight: 1.
      reduction: mean
    - 
      type: L1Loss
      # type: LPIPSLoss
      # type: PSNRLoss
      loss_weight: 1.
      reduction: mean
    -      
      type: PSNRLoss
      loss_weight: 1.
      reduction: mean
    - 
      type: PerceptualLoss
      loss_weight: 1.2
      reduction: mean

# validation settings
val:
  val_freq: !!float 2e2
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
