# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet-GoPro-width64-remove-fix
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    multi:
    -   
      type: PairedImageDataset
      dataroot_gt: ./remove_dataset_768/gt.lmdb
      dataroot_lq: ./remove_dataset_768/lq.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 448
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: ./remove_dataset3/gt.lmdb
    dataroot_lq: ./remove_dataset3/lq.lmdb
    io_backend:
      type: lmdb


network_g:
  # type: NAFNetLocal
  type: NAFNet
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  train_size: [1, 3, 448, 448]


# path
path:
  pretrain_network_g: experiments/NAFNet-GoPro-width64-remove/models/net_g_latest.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.95]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-9

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: ConcatLoss
    name:
    -
      # type: L1Loss
      # type: LPIPSLoss
      type: MS_SSIMLoss
      loss_weight: 1.
      reduction: mean
    - 
      type: L1Loss
      # type: LPIPSLoss
      # type: PSNRLoss
      loss_weight: 1.
      reduction: mean
    - 
      type: PerceptualLoss
      loss_weight: 0.3
      reduction: mean
      

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
